baseURL = 'https://shanedeconinck.be/'
languageCode = 'en-us'
title = 'Shane Deconinck'
theme = "paper"
[params]
    color = 'linen'  

    linkedin = 'shanedeconinck'
    rss = true
    
    avatar = 'shane.deconinck@gmail.com'
    name = 'Shane Deconinck'
    bio = 'Research in Web3, Trusted AI Agents, ICT4D | Full Stack Web Developer'
    monoDarkIcon = true 

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About me"
    url = "/about/"
    weight = 10